# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Publish Release

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up Java for publishing to Maven Central Repository
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        
    - name: Set pom versions to version specified by release tag
      run: mvn versions:set -DnewVersion=${{ github.event.release.tag_name }} versions:commit 

    - name: Install GPG Secret Key
      run: cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import

    - name: Publish to the Maven Central Repository
      run: mvn -P ossrh,sign -B deploy -s $GITHUB_WORKSPACE/release-settings.xml
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_JIRA_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_JIRA_PASSWORD }}
        GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
        GPG_KEYID: ${{ secrets.OSSRH_GPG_KEY_ID }}

    - name: Set up Java for publishing to GitHub Packages
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Publish to GitHub Packages Apache Maven
      run: mvn -P github -B deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
    - name: Roll pom version to next patch version
      run: mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT versions:commit

    - name: Commit New Snapshot Version (if changed)
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --global user.name 'mmadson'
          git config --global user.email 'code@matthewmadson.com'
          git add -A
          git commit -m "Rolling Maven Version to next snapshot"
          git push
        fi  
